#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Unity Skills Python Helper
# Auto-generated by UnitySkills

# CRITICAL: Fix Windows console encoding BEFORE any other imports or print statements
# This must be at the very top of the module to work correctly
import sys
if sys.platform == 'win32':
    import codecs
    if hasattr(sys.stdout, 'buffer'):
        sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'replace')
    if hasattr(sys.stderr, 'buffer'):
        sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'replace')

import requests
import time
import json
import os
from typing import Any, Dict, List, Optional

__version__ = "1.5.1"

UNITY_URL = "http://localhost:8090"
DEFAULT_PORT = 8090
PORT_RANGE_START = 8090
PORT_RANGE_END = 8100

# Timeout constants (seconds)
DEFAULT_CALL_TIMEOUT = 3600
HEALTH_TIMEOUT = 2
SCAN_TIMEOUT = 1

def get_registry_path():
    return os.path.join(os.path.expanduser("~"), ".unity_skills", "registry.json")


def _version_matches(actual_version: str, target: str) -> bool:
    if not actual_version or not target:
        return False
    cleaned = target.strip()
    if cleaned.lower().startswith("unity"):
        cleaned = cleaned[5:].strip()
    if not cleaned: return False
    if cleaned.split(".")[0] == "6" and not cleaned.startswith("6000"):
        return actual_version.startswith("6000.")
    return actual_version.startswith(cleaned)


class UnitySkills:
    def __init__(self, port: int = None, target: str = None, url: str = None, version: str = None, agent_id: str = None, timeout: int = None):
        self.url = url
        self.agent_id = agent_id or "Antigravity"
        self.timeout = timeout or DEFAULT_CALL_TIMEOUT
        self._session = requests.Session()
        self._session.headers.update({
            'X-Agent-Id': self.agent_id,
            'User-Agent': f'unity-skills-python/{__version__}',
        })

        if not self.url:
            if port:
                self.url = f"http://localhost:{port}"
            elif target:
                found_port = self._find_port_by_target(target)
                if found_port:
                    self.url = f"http://localhost:{found_port}"
                else:
                    raise ValueError(f"Could not find Unity instance matching '{target}' in registry.")
            elif version:
                found_port = self._find_port_by_version(version)
                if found_port:
                    self.url = f"http://localhost:{found_port}"
                else:
                    raise ValueError(f"Could not find Unity instance matching version '{version}'.")
            else:
                try:
                    found_port = self._find_first_available()
                    self.url = f"http://localhost:{found_port}"
                except:
                    self.url = f"http://localhost:{DEFAULT_PORT}"

        if not timeout:
            self._sync_timeout_from_server()

    def _sync_timeout_from_server(self):
        try:
            resp = requests.get(f"{self.url}/health", timeout=HEALTH_TIMEOUT)
            if resp.status_code == 200:
                minutes = resp.json().get('requestTimeoutMinutes')
                if minutes and isinstance(minutes, (int, float)) and minutes > 0:
                    self.timeout = int(minutes) * 60
        except: pass

    def _find_first_available(self) -> int:
        for port in range(PORT_RANGE_START, PORT_RANGE_END + 1):
            try:
                resp = requests.get(f"http://localhost:{port}/health", timeout=SCAN_TIMEOUT)
                if resp.status_code == 200: return port
            except: continue
        raise ConnectionError("No Unity instance found")

    def _find_port_by_target(self, target: str) -> Optional[int]:
        reg_path = get_registry_path()
        if not os.path.exists(reg_path): return None
        try:
            with open(reg_path, 'r') as f:
                data = json.load(f)
                for path, info in data.items():
                    if info.get('id') == target or info.get('name') == target:
                        return info.get('port')
                return None
        except: return None

    def _find_port_by_version(self, version: str) -> Optional[int]:
        reg_path = get_registry_path()
        if os.path.exists(reg_path):
            try:
                with open(reg_path, 'r') as f:
                    data = json.load(f)
                    for path, info in data.items():
                        if _version_matches(info.get('unityVersion'), version):
                            return info.get('port')
            except: pass
        return None

    def call(self, skill_name: str, verbose: bool = False, _retries: int = 3, _retry_delay: float = 2.0, **kwargs) -> Dict[str, Any]:
        for attempt in range(_retries + 1):
            try:
                kwargs['verbose'] = verbose
                response = self._session.post(
                    f"{self.url}/skill/{skill_name}",
                    data=json.dumps(kwargs, ensure_ascii=False).encode('utf-8'),
                    headers={'Content-Type': 'application/json; charset=utf-8'},
                    timeout=self.timeout
                )
                response.encoding = 'utf-8'
                data = response.json()
                if data.get('status') == 'success':
                    result = data.get('result', {})
                    normalized = {'success': True}
                    if isinstance(result, dict): normalized.update(result)
                    else: normalized['result'] = result
                    return normalized
                elif data.get('status') == 'error':
                    return {'success': False, 'error': data.get('error', 'Unknown error'), 'message': data.get('message', '')}
                else: return data
            except requests.exceptions.ConnectionError:
                if attempt < _retries:
                    time.sleep(_retry_delay * (attempt + 1))
                    continue
                return {'success': False, 'error': "Connection error"}
            except Exception as e:
                return {'success': False, 'error': str(e)}

_default_client = None
def _get_default_client():
    global _default_client
    if _default_client is None: _default_client = UnitySkills()
    return _default_client

def call_skill(skill_name: str, **kwargs) -> Dict[str, Any]:
    return _get_default_client().call(skill_name, **kwargs)

def health() -> bool:
    try:
        resp = requests.get(f"{_get_default_client().url}/health", timeout=HEALTH_TIMEOUT)
        return resp.json().get("status") == "ok"
    except: return False

def is_unity_running() -> bool: return health()

def wait_for_unity(timeout: float = 10.0) -> bool:
    start = time.time()
    while time.time() - start < timeout:
        if health(): return True
        time.sleep(1)
    return False

if __name__ == '__main__':
    print(json.dumps(_get_default_client().call("scene_get_info"), indent=2))
